/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.picturetransformmodule;

public class AIM implements AIMConstants {
  public static void setStreamer(Streamer streamer) {
    AIMJNI.setStreamer(Streamer.getCPtr(streamer), streamer);
  }

  public static Streamer getStreamer() {
    return new Streamer(AIMJNI.getStreamer(), false);
  }

}
