/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.picturetransformmodule;

public class AIMandroidReadSeqPort_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AIMandroidReadSeqPort_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AIMandroidReadSeqPort_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIMJNI.delete_AIMandroidReadSeqPort_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSuccess(boolean value) {
    AIMJNI.AIMandroidReadSeqPort_t_success_set(swigCPtr, this, value);
  }

  public boolean getSuccess() {
    return AIMJNI.AIMandroidReadSeqPort_t_success_get(swigCPtr, this);
  }

  public void setVal(vector_float value) {
    AIMJNI.AIMandroidReadSeqPort_t_val_set(swigCPtr, this, vector_float.getCPtr(value), value);
  }

  public vector_float getVal() {
    long cPtr = AIMJNI.AIMandroidReadSeqPort_t_val_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public AIMandroidReadSeqPort_t() {
    this(AIMJNI.new_AIMandroidReadSeqPort_t(), true);
  }

}
