/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.picturetransformmodule;

public interface AIMConstants {
  public final static int cimg_verbosity = AIMJNI.cimg_verbosity_get();
  public final static int cimg_display = AIMJNI.cimg_display_get();
}
