/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.picturetransformmodule;

public class AIMJNI {
  public final static native int cimg_verbosity_get();
  public final static native int cimg_display_get();
  public final static native void AIMandroidReadPort_t_success_set(long jarg1, AIMandroidReadPort_t jarg1_, boolean jarg2);
  public final static native boolean AIMandroidReadPort_t_success_get(long jarg1, AIMandroidReadPort_t jarg1_);
  public final static native void AIMandroidReadPort_t_val_set(long jarg1, AIMandroidReadPort_t jarg1_, int jarg2);
  public final static native int AIMandroidReadPort_t_val_get(long jarg1, AIMandroidReadPort_t jarg1_);
  public final static native long new_AIMandroidReadPort_t();
  public final static native void delete_AIMandroidReadPort_t(long jarg1);
  public final static native long new_PictureTransformModule();
  public final static native void PictureTransformModule_Tick(long jarg1, PictureTransformModule jarg1_);
  public final static native void PictureTransformModule_androidWritePort(long jarg1, PictureTransformModule jarg1_, int jarg2);
  public final static native long PictureTransformModule_androidReadPort(long jarg1, PictureTransformModule jarg1_);
  public final static native void delete_PictureTransformModule(long jarg1);
}
