/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.picturetransformmodule;

public class PictureTransformModule {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PictureTransformModule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PictureTransformModule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIMJNI.delete_PictureTransformModule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PictureTransformModule() {
    this(AIMJNI.new_PictureTransformModule(), true);
  }

  public void Tick() {
    AIMJNI.PictureTransformModule_Tick(swigCPtr, this);
  }

  public void androidWritePort(int in) {
    AIMJNI.PictureTransformModule_androidWritePort(swigCPtr, this, in);
  }

  public AIMandroidReadPort_t androidReadPort() {
    return new AIMandroidReadPort_t(AIMJNI.PictureTransformModule_androidReadPort(swigCPtr, this), true);
  }

  public void androidWriteSeqPort(vector_float in) {
    AIMJNI.PictureTransformModule_androidWriteSeqPort(swigCPtr, this, vector_float.getCPtr(in), in);
  }

  public AIMandroidReadSeqPort_t androidReadSeqPort() {
    return new AIMandroidReadSeqPort_t(AIMJNI.PictureTransformModule_androidReadSeqPort(swigCPtr, this), true);
  }

}
